title: Luda Korobenko
email: korobenko@reed.edu
description: >
  Lyudmila (Luda) Korobenko, Associate Professor of Mathematics at Reed College.
  Research on elliptic equations, degenerate elliptic operators, functional
  analysis, harmonic analysis, and metric measure spaces.
url: "https://mathetal.com"
baseurl: ""
plugins:
  - jekyll-sitemap
