title: Luda Korobenko
email: korobenko@reed.edu
description: >
  Associate Professor of Mathematics at Reed College.
  Research in PDEs, functional analysis, harmonic analysis,
  and metric measure spaces.
url: "" # set to https://<user>.github.io/<repo> when deployed
baseurl: "/luda-website"
